### ISSUE TITLE
Stream manager freezes when zk session expires

### ISSUE THREAD

**Issue by nwangtw** [apache/incubator-heron#2765] opened 2018-03-05 22:38 UTC
We got a user report in Twitter that a stream manager seemed to freeze after zk session expires.

The last lines in log are:
I0305 07:36:06.289669 31728 zkclient.cpp:59] ZKClient CallWatcher called with type SESSION_EVENT and state EXPIRED_SESSION_STATE
I0305 07:36:06.289674 31728 zkclient.cpp:289] ZKClient GlobalWatcher called with type SESSION_EVENT and state EXPIRED_SESSION_STATE
I0305 07:36:06.289706 31706 heron-zkstatemgr.cpp:343] Received an event, Type: SESSION_EVENT, State: EXPIRED_SESSION_STATE
I0305 07:36:06.289716 31706 heron-zkstatemgr.cpp:352] Deleting current zk client...

In code:
delete zkclient_;
LOG(INFO) << "Deleted current zk client, creating a new one...";
zkclient_ = zkclient_factory_->create(zkhostport_, eventLoop_, watch_event_cb_);
LOG(INFO) << "New zk client created";

The code above is in the watch event callback. I am wondering if client creation can be called in the callback or not, especially the eventloop and the callback function are used to create the client.

**Comment by maosongfu** [comment] 2018-03-05 22:42
@srkukarni Any idea what happened?

**Comment by huijunwu** [comment] 2020-07-11 20:11
should be fixed in #2908, cannot reproduce in the recent releases

**Closed by huijunwu** 2020-07-11 20:11 UTC
