### ISSUE TITLE
 Dockerize Heron Release

### ISSUE THREAD

**Issue by prabhuinbarajan** [apache/incubator-heron#1448] opened 2016-09-29 16:43 UTC
#### Dockerize Heron Release - as a Heron developer

I would like to containerize Heron Release so that it can be launched as a docker container with a configurable set of services. One should be able to launch heron core as a docker container with parameters that will specify supporting services needed to be launched by the executor
Ex heron container instance: 

```
docker run -it <heron-release-image> <topology-specific-docker-container-name> --link
zk:zookeeper -e heron.stream_manager=true -e heron.metrics_manager=true
            Ii.  
```

heron scheduler + tmaster instance : 

```
docker run -it <heron-release-image> <topology-specific-docker-container-name> --link zk:zookeeper -e heron.scheduler=true -e heron.tmaster=true heron.metrics_manager=true -e topology_parameters=.....
```

Note: we can build this image using bazel which has docker rules to build images. See https://docs.google.com/document/d/1pRhXp8LwPjUoY4jZBMmGcB_foqGuvsXmMlcgqjtfd10/edit

**Comment by Code0x58** [comment] 2020-07-15 17:30
I think this is a duplicate of https://github.com/apache/incubator-heron/issues/526 (now there are usable Dockerfiles in repo)

**Comment by nicknezis** [comment] 2020-07-15 19:24
Heron now supports building Heron container releases. Closing this older issue.

**Closed by nicknezis** 2020-07-15 19:24 UTC
Labels: Docker
