### ISSUE TITLE
fix macOS build way

### ISSUE THREAD

**Issue by sreev** [apache/incubator-heron#3638] opened 2020-11-29 05:23 UTC
**Is your feature request related to a problem? Please describe.**
build macos artifacts in a consistent way. update/upgrade to a small dependency is breaking the build.

**Describe the solution you'd like**
detail out the dependencies and versions.
make optional as possible
create new flag/options to keep an existing feature.
for eg. make pex optional.

**Describe alternatives you've considered**
open.

**Additional context**
none.

**Comment by sreev** [comment] 2020-11-29 05:24
Build from source on macOS bigsur fails. python3.9.0_2 / pip3 20.2.4.

```
DEPRECATION: The -b/--build/--build-dir/--build-directory option is deprecated. pip 20.3 will remove support for this functionality. A possible replacement is use the TMPDIR/TEMP/TMP environment variable, possibly combined with --no-clean. You can find discussion regarding this at https://github.com/pypa/pip/issues/8333.
ERROR: Package 'pex' requires a different Python: 3.9.0 not in '>=2.7,<3.9,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*'
INFO: Elapsed time: 228.509s, Critical Path: 85.54s
INFO: 876 processes: 153 internal, 723 local.
FAILED: Build did NOT complete successfully

WARNING: incubator-heron/heron/healthmgr/tests/java/BUILD:52:13: in srcs attribute of java_library rule //heron/healthmgr/tests/java:healthmgr-tests: please do not import '//heron/healthmgr/src/java:org/apache/heron/healthmgr/HealthManager.java' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'java_library', the error might have been caused by the macro implementation

warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: bazel-out/darwin-fastbuild/bin/heron/proto/libproto-cxx.a the table of contents is empty (no object file members in the library define global symbols)

ERROR: incubator-heron/tools/rules/pex/BUILD:53:8: Bootstrapping pex //tools/rules/pex:pex_wrapper failed (Exit 1): bash failed: error executing command 
  (cd /private/var/tmp/_bazel_svaddi/5513d20b4906d6e334d9ceb49a2d11d7/execroot/org_apache_heron && \
  exec env - \
    PATH='/usr/local/Cellar/python@3.9/3.9.0_2/bin:/usr/local/opt/openjdk@11/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Library/Apple/usr/bin' \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; OUTDIR=$(cd bazel-out/host/bin/tools/rules/pex && pwd)
```

**Comment by joshfischer1108** [comment] 2020-11-29 18:16
Can you please list the command that caused this failure so that it can be reproduced?

**Comment by joshfischer1108** [comment] 2020-11-30 02:48
It looks like you are using Python 3.9.  At this time we are supporting 3.8 at the highest.   I just ran the commands listed above and was able to successfully build on my local.

If using brew on OSX you can install Python 3.8 and switch to it.  Note: The following commands may not be 100% correct.

To install 
```
$  brew install python@3.8
```
To switch it would be something like the below 
```
$  brew switch python 3.8 
```

**Comment by joshfischer1108** [comment] 2020-12-08 02:09
@sreev Is your issue resolved?

**Comment by Code0x58** [comment] 2020-12-08 15:42
I created a [PR](3646) that should allow you to run on a system with python 3.9 installed, so you could test out the branch @sreev

**Comment by nicknezis** [comment] 2021-03-04 22:22
I'm closing this issue. I believe the build works on Python 3.8, and with #3646 we can move to Python 3.9. But we don't need to keep this open. @sreev if you do get around to helping test #3646, just leave a comment on that pull request. If not, no worries.

**Closed by nicknezis** 2021-03-04 22:22 UTC
